### ISSUE TITLE
TimeoutError: Timed out after 30 seconds while waiting for node to startup. 

### ISSUE THREAD

**Issue by lysanderism** [xieh97/dcase2022-audio-retrieval#2]
**hello author, I encouter with the ray init problem, can you share you solution? thanks a lot**
Traceback (most recent call last):
  File "/home/whl/anaconda3/envs/DESED/lib/python3.9/site-packages/ray/_private/node.py", line 292, in __init__
    ray._private.services.wait_for_node(
  File "/home/whl/anaconda3/envs/DESED/lib/python3.9/site-packages/ray/_private/services.py", line 460, in wait_for_node
    raise TimeoutError(
TimeoutError: Timed out after 30 seconds while waiting for node to startup. Did not find socket name tmp/session_2023-05-08_09-49-19_544621_18001/sockets/plasma_store in the list of object store socket names.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/whl/anaconda3/envs/DESED/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/whl/anaconda3/envs/DESED/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/whl/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/home/whl/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/home/whl/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/home/whl/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/whl/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/whl/.vscode-server/extensions/ms-python.python-2022.16.1/pythonFiles/lib/python/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "train.py", line 88, in <module>
    ray.init(**ray_conf["init_args"])
  File "/home/whl/anaconda3/envs/DESED/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/whl/anaconda3/envs/DESED/lib/python3.9/site-packages/ray/_private/worker.py", line 1523, in init
    _global_node = ray._private.node.Node(
  File "/home/whl/anaconda3/envs/DESED/lib/python3.9/site-packages/ray/_private/node.py", line 297, in __init__
    raise Exception(
Exception: The current node timed out during startup. This could happen because some of the Ray processes failed to startup.

**Comment by xieh97** [comment]
Hi, it seems this problem was caused by "ray.init(**ray_conf["init_args"])".

Without further info about your code, I would first check:
1) if parameters in "conf.yaml" were set correctly,
2) if the library "ray" was installed with the right version (1.6.0).
